export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const WHOAMI = "WHOAMI";

export const PRELOAD_INFO_INIT = "PRELOAD_INFO_INIT";
export const PRELOAD_INFO_SUCCESS = "PRELOAD_INFO_SUCCESS";
export const PRELOAD_INFO_FAILURE = "PRELOAD_INFO_FAILURE";

export const DISMISS_ERRORS = "DISMISS_ERRORS";
