export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const WHOAMI_REQUEST = "WHOAMI_REQUEST";
export const WHOAMI = "WHOAMI";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const PRELOAD_INFO_INIT = "PRELOAD_INFO_INIT";
export const PRELOAD_INFO_SUCCESS = "PRELOAD_INFO_SUCCESS";
export const PRELOAD_INFO_FAILURE = "PRELOAD_INFO_FAILURE";
export const SHOW_TAGS_FORM = "SHOW_TAGS_FORM";

export const DISMISS_ERRORS = "DISMISS_ERRORS";
export const DISMISS_SUCCESS = "DISMISS_SUCCESS";

//DATA
export const REQUEST_ALL_UPLOADED_TRACKS = "REQUEST_ALL_UPLOADED_TRACKS";
export const SET_TRACKS = "SET_TRACKS";
export const DATA_REQUEST_FAILURE = "DATA_REQUEST_FAILURE";
//PLAYER
export const SET_PLAYER_TRACK_PLAYBACK = "SET_PLAYER_TRACK_PLAYBACK";
export const SET_PLAYER_TRACK_COVER = "SET_PLAYER_TRACK_COVER";
export const STOP_PLAYER = "STOP_PLAYER";
export const PLAY_PLAYER = "PLAY_PLAYER";
export const INIT_QUEUE = "INIT QUEUE";